### ISSUE TITLE
Dynamic route params interfere with BetterAuth wildcard routes

### ISSUE THREAD

**Issue by frhnfrq** [honojs/hono#4124]
### What version of Hono are you using?

4.7.8

### What runtime/platform is your app running on? (with version if possible)

Bun

### What steps can reproduce the bug?

Let's say we have these routes,

```ts
export const devRouter = new Hono();

devRouter.get("/greet", async (c) => {
  return c.json({greet: "hello"});
});

devRouter.get("/:test", async (c) => {
  const param = c.req.param("test");
  return c.json({ param });
});

```
/greet is properly prioritized, as it should, BUT this breaks better auth. 

Here is the better auth route,
```ts
const app = new Hono().basePath("/api");
app.on(["POST", "GET"], "/auth/**", (c) => auth.handler(c.req.raw));
```

When I try to use the better auth endpoints, I get hit by this error "404 Not Found"

I think this has something to do with the router with the basic preset of Hono. 

When I switch Hono to the hono/quick preset, better auth endpoints start working. 

### What is the expected behavior?

better auth endpoints should work as usual

### What do you see instead?

I get hit by this error "404 Not Found"

### Additional information

Package versions:

better-auth: "^1.2.4"
hono: "^4.7.8"

**Comment by yusukebe** [comment]
@frhnfrq 

I think this is a better-auth side issue, not a Hono-side issue. For example, see the following code. In this case, `auth.handler` will return a blank `not found` response, which is not the Hono app's `not found` response. We can't fix it.

```ts
import { betterAuth } from 'better-auth'
import { Hono } from 'hono'

const auth = betterAuth({})

const app = new Hono()

app.get('/auth/**', (c) => {
  return auth.handler(c.req.raw)
})

const res = await app.request('/auth/foo')

console.log(res.status) // `404`
console.log(await res.text()) // null
```

**Comment by yusukebe** [comment]
I'll close this issue since there has been no response.

**Comment by allyusd** [comment]
TL;DR: try changing ** to *

Full details below:
I ran into a similar issue.

Originally:

```ts
app.on(["POST", "GET"], "/api/auth/**", (c) => auth.handler(c.req.raw));
```

After adding a route before it:

```ts
app.on(["POST", "GET"], "/api/auth/aaa/bbb", async (c) => { 
  // do something 
});

app.on(["POST", "GET"], "/api/auth/**", (c) => auth.handler(c.req.raw));
```

Better Auth APIs returned 404 Not Found.

Following the docs:
https://www.better-auth.com/docs/integrations/hono

Changing the route to:

```ts
app.on(["POST", "GET"], "/api/auth/aaa/bbb", async (c) => { 
  // do something 
});

app.on(["POST", "GET"], "/api/auth/*", (c) => auth.handler(c.req.raw));
```

fixed the issue.

Note: Originally used **; switching to * resolves the problem. Sharing for reference.

**Comment by tawfekov** [comment]
its still 404 even I've made sure to follow all instructions 


my only diff is I've multi-sub hono apps

**Comment by hxtnv** [comment]
cloned the repo from hono docs (https://github.com/catalinpit/example-app/tree/main), tried changing `**` to `*` and it still doesnt work :/
